### ISSUE TITLE
gnuplot> set terminal

### ISSUE THREAD

**Issue by nikadon** [spin-scenario/spin-scenario#1]
Is there an option (a switch that can be triggered by user) to change the default terminal from **qt** to say **png**? On some systems, this may be the last resort...

**Comment by spin-scenario** [comment]
A new function `output_terminal{}` was added for this issue. User may use this API when they wish to save the visualized data into files. Options include `png`, `eps`, `svg` and `tex`.  E.g. `output_terminal{"png"} ` will generate png outputs.  An example using this option can be found [here](https://github.com/spin-scenario/spin-scenario/blob/master/test/seq/fid.lua).
[Commits](https://github.com/spin-scenario/spin-scenario/commit/60c6254ec3dda6cb16b7bdf1e0041d65659f6135) for this issue.
